name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Snyk Open Source Test (SCA)
        run: npx snyk test --org=9ef6206b-6bf4-4ce0-8478-8b5d99108524
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code Test (SAST)
        run: npx snyk code test --org=9ef6206b-6bf4-4ce0-8478-8b5d99108524
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
